### PR TITLE
feat(games): added score display

### PR DESCRIPTION
**Pull request by XcapeEst**

### CODE REVIEW

**Comment by XcapeEst** [comment]
In a hurry, I hadn't tested these changes, so I relied on your overview.

**Comment by garrappachc** [comment]
There were some fixes needed, I'm closing this PR and opening a new one: https://github.com/tf2pickup-org/client/pull/2415

**Comment by XcapeEst** [comment]
Why did you have to open a new PR?

**Comment by garrappachc** [comment]
> Why did you have to open a new PR?

Because I can't modify branch of PR that I didn't open.

**Pull request closed without merging**
